# Copyright (c) 2024 Stappler LLC <admin@stappler.dev>
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.

MODULE_STAPPLER_WEBSERVER_WEBSERVER_DEFINED_IN := $(TOOLKIT_MODULE_PATH)
MODULE_STAPPLER_WEBSERVER_WEBSERVER_PRECOMPILED_HEADERS :=
MODULE_STAPPLER_WEBSERVER_WEBSERVER_SRCS_DIRS :=
MODULE_STAPPLER_WEBSERVER_WEBSERVER_SRCS_OBJS := \
	$(WEBSERVER_MODULE_DIR)/webserver/gen/SPWebVirtual.cpp \
	$(WEBSERVER_MODULE_DIR)/webserver/SPWeb.scu.cpp \
	$(WEBSERVER_MODULE_DIR)/webserver/stappler-webserver.wit

MODULE_STAPPLER_WEBSERVER_WEBSERVER_INCLUDES_DIRS := $(WEBSERVER_MODULE_DIR)/webserver
MODULE_STAPPLER_WEBSERVER_WEBSERVER_INCLUDES_OBJS :=

MODULE_STAPPLER_WEBSERVER_WEBSERVER_DEPENDS_ON := \
	stappler_filesystem stappler_data stappler_db stappler_crypto stappler_webserver_pug stappler_brotli_lib stappler_bitmap stappler_wasm

MODULE_STAPPLER_WEBSERVER_WEBSERVER_FLAGS := \
	-DWEBSERVER_VERSION_API=$(WEBSERVER_VERSION_API) \
	-DWEBSERVER_VERSION_REV=$(WEBSERVER_VERSION_REV)


# module name resolution
MODULE_stappler_webserver_webserver := MODULE_STAPPLER_WEBSERVER_WEBSERVER

MODULE_STAPPLER_WEBSERVER_WEBSERVER__VIRTUAL_ROOT := $(WEBSERVER_MODULE_DIR)/webserver
MODULE_STAPPLER_WEBSERVER_WEBSERVER__VIRTUAL_SRCS := \
	$(wildcard $(MODULE_STAPPLER_WEBSERVER_WEBSERVER__VIRTUAL_ROOT)/virtual/js/*.js) \
	$(wildcard $(MODULE_STAPPLER_WEBSERVER_WEBSERVER__VIRTUAL_ROOT)/virtual/css/*.css) \
	$(wildcard $(MODULE_STAPPLER_WEBSERVER_WEBSERVER__VIRTUAL_ROOT)/virtual/html/*.html) \
	$(wildcard $(MODULE_STAPPLER_WEBSERVER_WEBSERVER__VIRTUAL_ROOT)/virtual/html/*.pug)

$(abspath $(WEBSERVER_MODULE_DIR)/webserver/gen/SPWebVirtual.cpp): $(MODULE_STAPPLER_WEBSERVER_WEBSERVER__VIRTUAL_SRCS)
	@mkdir -p $(WEBSERVER_MODULE_DIR)/webserver/gen
	@printf '// Files for virtual filesystem\n// Autogenerated by makefile (webserver.mk)\n///@ SP_EXCLUDE\n' > $@
	@printf '#include "SPWebVirtualFile.h"\nnamespace STAPPLER_VERSIONIZED stappler::web {\n' >> $@
	@printf "\nconst char * getCompileDate() { return __DATE__ \" \" __TIME__; }\n" >> $@
	@printf "Time getCompileUnixTime() { return SP_COMPILE_TIME; }" >> $@
	@for file in $^; do \
		printf "\n\n// $$file \nstatic VirtualFile\n" >> $@; \
		printf $$file | sed "s:^$(MODULE_STAPPLER_WEBSERVER_WEBSERVER__VIRTUAL_ROOT)/virtual::" | tr "/." _ >> $@; \
		printf " = VirtualFile::add(\"" >> $@; \
		printf $$file | sed "s:^$(MODULE_STAPPLER_WEBSERVER_WEBSERVER__VIRTUAL_ROOT)/virtual::" >> $@; \
		printf "\", R\"VirtualFile(" >> $@; \
		cat $$file >> $@; \
		printf ")VirtualFile\");" >> $@; \
		echo "[VirtualFile] $$file > SPWebVirtual.cpp"  | sed "s:$(MODULE_STAPPLER_WEBSERVER_WEBSERVER__VIRTUAL_ROOT)::"; \
	done
	@echo '}' >> $@
